services:
    _defaults:
        autowire: false
        autoconfigure: false

    ThreeBRS\SyliusDocumentationPlugin\Menu\AdminMenuListener:
        arguments:
            $translator: '@translator'
            $documentationIndexRoute: 'threebrs_sylius_documentation_admin_index'
        tags:
            - { name: kernel.event_subscriber }

    League\CommonMark\CommonMarkConverter: ~

    ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationControllerInterface:
        class: ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationController
        public: true
        arguments:
            $twig: '@twig'
            $converter: '@League\CommonMark\CommonMarkConverter'
            $docsPath: '%threebrs_sylius_documentation.docs_path%'
            $projectDir: '%kernel.project_dir%'
            $router: '@router'
            $docsIndexRoute: 'threebrs_sylius_documentation_admin_index'
            $docsShowRoute: 'threebrs_sylius_documentation_admin_show'
            $docsImageRoute: 'threebrs_sylius_documentation_admin_image'

    ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationController:
        alias: ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationControllerInterface
        public: true
